import type { Kajian, Location, User } from "@/types";

/**
 * Mock dataset grounded in real Bandung landmarks so the map looks and
 * feels like a real deployment during development. Ustadz names are
 * fictional placeholders — replace with real, consented data before
 * launch.
 */

export const mockLocations: Location[] = [
  {
    id: "loc-1",
    name: "Masjid Raya Bandung",
    address: "Jl. Dalem Kaum No.14, Balonggede, Regol",
    city: "Bandung",
    province: "Jawa Barat",
    lat: -6.9218,
    lng: 107.607,
    imageUrl:
      "https://images.unsplash.com/photo-1591825381117-c9d3c9c1a3f8?q=80&w=800&auto=format&fit=crop",
    contactPhone: "022-4234892",
    createdAt: "2026-01-05T02:00:00.000Z",
    updatedAt: "2026-06-01T02:00:00.000Z",
  },
  {
    id: "loc-2",
    name: "Masjid Salman ITB",
    address: "Jl. Ganesa No.7, Lb. Siliwangi, Coblong",
    city: "Bandung",
    province: "Jawa Barat",
    lat: -6.8915,
    lng: 107.6107,
    contactPhone: "022-2504033",
    createdAt: "2026-01-05T02:00:00.000Z",
    updatedAt: "2026-05-20T02:00:00.000Z",
  },
  {
    id: "loc-3",
    name: "Masjid Al-Ukhuwwah",
    address: "Jl. Wastukancana No.34, Babakan Ciamis, Sumur Bandung",
    city: "Bandung",
    province: "Jawa Barat",
    lat: -6.9034,
    lng: 107.6186,
    createdAt: "2026-01-12T02:00:00.000Z",
    updatedAt: "2026-04-18T02:00:00.000Z",
  },
  {
    id: "loc-4",
    name: "Masjid PUSDAI Jawa Barat",
    address: "Jl. Diponegoro No.63, Citarum, Bandung Wetan",
    city: "Bandung",
    province: "Jawa Barat",
    lat: -6.8998,
    lng: 107.6247,
    contactPhone: "022-7207736",
    createdAt: "2026-02-01T02:00:00.000Z",
    updatedAt: "2026-06-11T02:00:00.000Z",
  },
  {
    id: "loc-5",
    name: "Masjid Daarut Tauhiid",
    address: "Jl. Gegerkalong Girang No.38, Isola, Sukasari",
    city: "Bandung",
    province: "Jawa Barat",
    lat: -6.8657,
    lng: 107.5896,
    createdAt: "2026-01-20T02:00:00.000Z",
    updatedAt: "2026-05-02T02:00:00.000Z",
  },
  {
    id: "loc-6",
    name: "Masjid Raya Habiburrahman PT DI",
    address: "Jl. Pajajaran No.154, Husein Sastranegara, Cicendo",
    city: "Bandung",
    province: "Jawa Barat",
    lat: -6.9024,
    lng: 107.5776,
    createdAt: "2026-02-14T02:00:00.000Z",
    updatedAt: "2026-03-30T02:00:00.000Z",
  },
];

/** Two upcoming one-off dates computed relative to "today" so the demo
 *  never looks stale, however far in the future it's opened. */
const today = new Date();
const inDays = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return toISO(d);
};
function toISO(d: Date) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(
    d.getDate()
  ).padStart(2, "0")}`;
}

export const mockKajian: Kajian[] = [
  {
    id: "kj-1",
    locationId: "loc-1",
    title: "Kajian Tafsir Al-Qur'an Ba'da Subuh",
    ustadz: "Ustadz Fauzan Ridwan, Lc.",
    category: "Tafsir Al-Qur'an",
    frequency: "rutin",
    dayOfWeek: "minggu",
    startTime: "05:15",
    endTime: "06:30",
    description:
      "Kajian rutin pekanan membahas tafsir Al-Qur'an juz demi juz dengan pendekatan tematik, terbuka untuk umum, ikhwan dan akhwat (dipisah shaf).",
    contactPerson: "Sekretariat Masjid Raya Bandung",
    contactPhone: "022-4234892",
    isActive: true,
    createdAt: "2026-01-10T02:00:00.000Z",
    updatedAt: "2026-06-01T02:00:00.000Z",
    createdBy: "admin-1",
  },
  {
    id: "kj-2",
    locationId: "loc-1",
    title: "Kajian Fiqih Kontemporer",
    ustadz: "Ustadz Hilman Taufiq, M.Ag.",
    category: "Fiqih",
    frequency: "rutin",
    dayOfWeek: "rabu",
    startTime: "19:45",
    endTime: "21:00",
    description:
      "Membahas persoalan fiqih yang relevan dengan kehidupan sehari-hari — muamalah, keuangan syariah, dan isu kontemporer lainnya.",
    contactPerson: "Sekretariat Masjid Raya Bandung",
    contactPhone: "022-4234892",
    isActive: true,
    createdAt: "2026-01-10T02:00:00.000Z",
    updatedAt: "2026-05-14T02:00:00.000Z",
    createdBy: "admin-1",
  },
  {
    id: "kj-3",
    locationId: "loc-2",
    title: "Kajian Aqidah untuk Mahasiswa",
    ustadz: "Ustadz Zaki Abror, Lc., M.A.",
    category: "Aqidah",
    frequency: "rutin",
    dayOfWeek: "kamis",
    startTime: "19:30",
    endTime: "21:00",
    description:
      "Kajian pekanan Masjid Salman ITB membahas dasar-dasar aqidah Ahlus Sunnah wal Jama'ah, dikemas ringan untuk mahasiswa dan pemula.",
    contactPerson: "Divisi Dakwah Salman ITB",
    contactPhone: "022-2504033",
    isActive: true,
    createdAt: "2026-01-15T02:00:00.000Z",
    updatedAt: "2026-06-05T02:00:00.000Z",
    createdBy: "admin-2",
  },
  {
    id: "kj-4",
    locationId: "loc-2",
    title: "Kajian Muslimah: Fiqih Wanita",
    ustadz: "Ustadzah Nadia Rahman, Lc.",
    category: "Kajian Muslimah",
    frequency: "rutin",
    dayOfWeek: "sabtu",
    startTime: "09:00",
    endTime: "11:00",
    description:
      "Kajian khusus muslimah membahas fiqih wanita: thaharah, haid, dan adab-adab keseharian. Tersedia penitipan anak.",
    contactPerson: "Divisi Muslimah Salman ITB",
    isActive: true,
    createdAt: "2026-02-01T02:00:00.000Z",
    updatedAt: "2026-05-22T02:00:00.000Z",
    createdBy: "admin-2",
  },
  {
    id: "kj-5",
    locationId: "loc-3",
    title: "Kajian Hadits Arba'in An-Nawawi",
    ustadz: "Ustadz Fauzan Ridwan, Lc.",
    category: "Hadits",
    frequency: "rutin",
    dayOfWeek: "selasa",
    startTime: "19:30",
    endTime: "20:45",
    description:
      "Tadabbur dan penjelasan Hadits Arba'in An-Nawawi satu per satu, disertai sesi tanya jawab.",
    contactPerson: "Takmir Masjid Al-Ukhuwwah",
    isActive: true,
    createdAt: "2026-02-03T02:00:00.000Z",
    updatedAt: "2026-04-18T02:00:00.000Z",
    createdBy: "admin-3",
  },
  {
    id: "kj-6",
    locationId: "loc-4",
    title: "Tabligh Akbar: Meneladani Akhlak Nabi",
    ustadz: "Ustadz Hilman Taufiq, M.Ag.",
    category: "Akhlak & Tazkiyah",
    frequency: "insidental",
    date: inDays(4),
    startTime: "08:00",
    endTime: "11:00",
    description:
      "Kajian akbar dalam rangka peringatan Maulid Nabi Muhammad ﷺ, terbuka untuk umum dengan konsumsi disediakan panitia.",
    contactPerson: "Panitia Pusdai Jawa Barat",
    contactPhone: "022-7207736",
    posterUrl:
      "https://images.unsplash.com/photo-1585129777188-91ff8db6e1a2?q=80&w=800&auto=format&fit=crop",
    isActive: true,
    createdAt: "2026-06-01T02:00:00.000Z",
    updatedAt: "2026-06-11T02:00:00.000Z",
    createdBy: "admin-4",
  },
  {
    id: "kj-7",
    locationId: "loc-4",
    title: "Kajian Sirah Nabawiyah",
    ustadz: "Ustadz Zaki Abror, Lc., M.A.",
    category: "Sirah Nabawiyah",
    frequency: "rutin",
    dayOfWeek: "senin",
    startTime: "19:30",
    endTime: "21:00",
    description:
      "Napak tilas perjalanan hidup Rasulullah ﷺ dari periode Makkah hingga Madinah, dibawakan secara kronologis.",
    contactPerson: "Takmir Pusdai Jawa Barat",
    isActive: true,
    createdAt: "2026-02-20T02:00:00.000Z",
    updatedAt: "2026-05-30T02:00:00.000Z",
    createdBy: "admin-4",
  },
  {
    id: "kj-8",
    locationId: "loc-5",
    title: "Kajian Remaja: Muda Berkarya, Taat Beragama",
    ustadz: "Ustadz Rizky Maulana, S.Sos.",
    category: "Kajian Remaja",
    frequency: "rutin",
    dayOfWeek: "jumat",
    startTime: "20:00",
    endTime: "21:30",
    description:
      "Ruang diskusi santai untuk remaja & pemuda seputar agama, produktivitas, dan pengembangan diri.",
    contactPerson: "Bidang Kepemudaan DT",
    isActive: true,
    createdAt: "2026-01-25T02:00:00.000Z",
    updatedAt: "2026-06-02T02:00:00.000Z",
    createdBy: "admin-5",
  },
  {
    id: "kj-9",
    locationId: "loc-5",
    title: "Kajian Umum Ba'da Maghrib",
    ustadz: "Ustadz Fauzan Ridwan, Lc.",
    category: "Kajian Umum",
    frequency: "rutin",
    dayOfWeek: "minggu",
    startTime: "18:15",
    endTime: "19:15",
    description:
      "Kajian umum bertema ringan seputar ibadah harian, terbuka untuk seluruh jamaah tanpa perlu pendaftaran.",
    contactPerson: "Takmir Daarut Tauhiid",
    isActive: true,
    createdAt: "2026-01-25T02:00:00.000Z",
    updatedAt: "2026-05-19T02:00:00.000Z",
    createdBy: "admin-5",
  },
  {
    id: "kj-10",
    locationId: "loc-6",
    title: "Kajian Muamalah & Ekonomi Syariah",
    ustadz: "Ustadz Zaki Abror, Lc., M.A.",
    category: "Muamalah",
    frequency: "insidental",
    date: inDays(9),
    startTime: "13:00",
    endTime: "15:00",
    description:
      "Membahas praktik jual-beli, riba, dan akad-akad syariah yang relevan bagi karyawan dan pelaku usaha.",
    contactPerson: "Takmir Masjid Habiburrahman",
    isActive: true,
    createdAt: "2026-03-01T02:00:00.000Z",
    updatedAt: "2026-06-08T02:00:00.000Z",
    createdBy: "admin-6",
  },
  {
    id: "kj-11",
    locationId: "loc-6",
    title: "Kajian Aqidah Ahlus Sunnah",
    ustadz: "Ustadz Hilman Taufiq, M.Ag.",
    category: "Aqidah",
    frequency: "rutin",
    dayOfWeek: "kamis",
    startTime: "19:30",
    endTime: "20:45",
    description:
      "Pembahasan rukun iman secara sistematis bagi jamaah umum sekitar area PT DI dan Husein Sastranegara.",
    contactPerson: "Takmir Masjid Habiburrahman",
    isActive: true,
    createdAt: "2026-03-01T02:00:00.000Z",
    updatedAt: "2026-05-25T02:00:00.000Z",
    createdBy: "admin-6",
  },
];

export const mockUsers: User[] = [
  {
    id: "super-1",
    name: "Admin Pusat",
    email: "superadmin@kajianmap.id",
    role: "super_admin",
    assignedLocationIds: [],
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "admin-1",
    name: "Ridho Prasetya",
    email: "admin.masjidraya@kajianmap.id",
    role: "admin_masjid",
    assignedLocationIds: ["loc-1"],
    isActive: true,
    createdAt: "2026-01-06T00:00:00.000Z",
  },
  {
    id: "admin-2",
    name: "Sarah Amalia",
    email: "admin.salman@kajianmap.id",
    role: "admin_masjid",
    assignedLocationIds: ["loc-2"],
    isActive: true,
    createdAt: "2026-01-16T00:00:00.000Z",
  },
  {
    id: "admin-3",
    name: "Yusuf Firmansyah",
    email: "admin.ukhuwwah@kajianmap.id",
    role: "admin_masjid",
    assignedLocationIds: ["loc-3"],
    isActive: true,
    createdAt: "2026-02-04T00:00:00.000Z",
  },
  {
    id: "admin-4",
    name: "Dewi Kurniawati",
    email: "admin.pusdai@kajianmap.id",
    role: "admin_masjid",
    assignedLocationIds: ["loc-4"],
    isActive: true,
    createdAt: "2026-02-02T00:00:00.000Z",
  },
  {
    id: "admin-5",
    name: "Bagas Wirawan",
    email: "admin.dt@kajianmap.id",
    role: "admin_masjid",
    assignedLocationIds: ["loc-5"],
    isActive: true,
    createdAt: "2026-01-26T00:00:00.000Z",
  },
  {
    id: "admin-6",
    name: "Farah Utami",
    email: "admin.habiburrahman@kajianmap.id",
    role: "admin_masjid",
    assignedLocationIds: ["loc-6"],
    isActive: true,
    createdAt: "2026-03-02T00:00:00.000Z",
  },
];

/** Default map center: Bandung city center. */
export const DEFAULT_MAP_CENTER: [number, number] = [-6.9218, 107.6191];
export const DEFAULT_MAP_ZOOM = 13;
